version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: docker build -t isrp/isrp-api:latest .
     - run: docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
     - run: docker push isrp/isrp-api:latest
